### ISSUE TITLE
Revider status visning til elever

### ISSUE THREAD

**Issue by kuliktomas** [janhebnes/startlist.club#101]
Det skal være muligt at se elev status inklusiv komentar, manouvre og de andre information direkte i status side til elev flyvninger.  Nu skal instruktør færst åbne en ny flyving til at se alle de information om en elev.

**Comment by plaursen** [comment]
Du kan se elevstatus via topmenu->logbog->Uddannelsesflyvninger og Uddannelsesstatus.

![image](https://user-images.githubusercontent.com/48796590/112205922-a4156700-8c15-11eb-81d6-774a05cbb5a8.png)


Hvad mener du at der mangler ud over det ?

**Comment by Micro1st** [comment]
Hopper lige ind her.
Hvis jeg klikker ind på Uddannelsesstatus, kan jeg se hvor eleven mangler
nogen deløvelser, lad os sige G5. Men jeg kan ikke se hvilke deløvelser det
er, før jeg laver en start til eleven?






Den tir. 23. mar. 2021 kl. 20.24 skrev plaursen ***@***.***>:

**Comment by plaursen** [comment]
Nej, det er vel rigtig nok. Hvis du klikker på Øvelsen (G5), kan du se hvad der er fløjet på den øvelse, men korrekt, det giver ikke samme overblik.

Hele den side var lidt en eftertanke (netop fordi man ellers skulle oprette en start), så der er nok et forbedringspotentiale.

I praksis har man vel dog mest brug for det overblik når man skal briefe eleven / planlægge turen, dvs starten kan allerede være oprettet.
UI for de der topmenu-lister er ikke optimeret til (eller tiltænkt) cockpitbrug.

**Comment by plaursen** [comment]
Kom gerne med et forslag til hvordan det kunne se ud :)

**Comment by Micro1st** [comment]
Korrekt. Et er mine argumenter for at benyttede digital elevmappe, er at
kunne forberede flyvningen i forvejen. fx aftenen før I-vagt.

Et forslag er at kunne komme direkte ind i trainingLog/Edit.. Det er sådan
en fin oversigt, men man er nødt til at opret en flyvning først.
Et andet forslag kunne være at skrive hvad der mangler i listen:

[image: image.png]

Men ved ikke hvor meget arbejde der er i at lave det? :)

Den tir. 23. mar. 2021 kl. 21.06 skrev plaursen ***@***.***>:

**Comment by plaursen** [comment]
Det var da et glimrende argument :)  
Det er nok ikke så praktisk at 'genbruge' det view til oversigtsformål - det er ret tæt koblet til en konkret flyvning, og indeholder en del muligheder for redigering, som der så skulle blokeres for.

Men man kan jo sagtens genbruge dele af UI'et til et 'read-only' view (jeg vil gætte på at du finde den 'formelle' del med øvelser/deløvelser mest interessant ?) Det vil ikke være voldsomt tidskrævende, men det bliver nok ikke i denne uge :)

Jeg kan desværre ikke se det billede du har vedhæftet.

**Comment by Micro1st** [comment]
Okay, billedet var under uddannelsesstatus/G5/"trykker på flyvningen" også
får man detaljer frem. Man kan se de deløvelser eleven har været igennem,
men man kan ikke se hvad eleven mangler i G5 for at få den grøn.

Kan man lave en udtræk over dem og præsentere på listen, ville det være en
flot oversigt.



Den tir. 23. mar. 2021 kl. 21.19 skrev plaursen ***@***.***>:
