### ISSUE TITLE
FLARM OGN API er betalings produkt i 2020 så integration virker ikke længere

### ISSUE THREAD

**Issue by janhebnes** [janhebnes/startlist.club#105]
Slår man Registreret OGN FlightLog Lufthavn på et Sted og har klubben dette sted som hjemme sted bliver der ved redigering af flyvninger vist dagens FLARM baseret starter, så man hurtigt kan vælge oplysninger fra FLARM listen og udfylde felter med. 

2020 blev året hvor ktrax har valgt at lave betalingsløsning på toppen af deres OGN data...

Parsing from OGN failed (https://ktrax.kisstech.ch/logbook/?id=EKNF&tz=1&day=2021-03-24&units=metric&shorthand=true&showtype=true&fstatus=all&ftype=all&disp=cs&showcrew=false)

![image](https://user-images.githubusercontent.com/910301/112303555-b1296900-8c9c-11eb-9933-e6109f6b677e.png)

----

https://ktrax.kisstech.ch/contribute?airport=EKRK&referrer=logbook

Det er uvist om man kan opsætte det så en klub/startsted kan betale noget for at vi via startlist.club kan hente og abonnere på dataen.

**Comment by Micro1st** [comment]
Kan man benytte https://logbook.ibisek.com/loc/EKHM/2020-09-19 i stedet for?

Den ons. 24. mar. 2021 kl. 12.40 skrev Jan Hebnes ***@***.***

**Comment by plaursen** [comment]
Jeg tror at NSF betaler sig fra det - check evt med Torben Søemod, NSF

**Comment by janhebnes** [comment]
> Kan man benytte https://logbook.ibisek.com/loc/EKHM/2020-09-19 i stedet for? 

Det var et rigtig fint alternativ. 
Det er noget som skal ændres i den eksterne nuget pakke styret fra https://github.com/janhebnes/OGN.FlightLog.Client

Den mest optimale model ville være hvis vi kunne tag data direkte fra OGN netværket, men kender ikke omfanget af en sådan forbindelse.

**Comment by janhebnes** [comment]
> Jeg tror at NSF betaler sig fra det - check evt med Torben Søemod, NSF

Hvis der er betaling så kommer der måske en dedikeret api key, som hvert landingssted så skal tilknyttes.
Bør sikres også at der er mulighed for at videre distribuere.

**Comment by Micro1st** [comment]
En anden mulighed https://github.com/snip/flightLGo
Skal installeres på hver flyveplads også kan den sende til
https://flightlog.glidernet.org/ eller en anden server



Den ons. 24. mar. 2021 kl. 12.49 skrev Jan Hebnes ***@***.***

**Comment by janhebnes** [comment]
Martin Jensen har henledt opmærksomheden på 
https://github.com/skyhop/Aprs
https://skyhop.org/

**Comment by janhebnes** [comment]
Et andet interessant projekt ligger på https://github.com/flightlog

**Comment by plaursen** [comment]
Vi har nu implementeret et alternativ, så jeg tillader mig at lukke denne.
