### ISSUE TITLE
Langsomt visning af uddannelsesstatus

### ISSUE THREAD

**Issue by Micro1st** [janhebnes/startlist.club#118]
Det tager ca. 14-15 sek at få uddannelsesstatus listen frem. Kan det gøres hurtigere?

**Comment by janhebnes** [comment]
(_Husk debug tilstand smider sql i trace_)

**Comment by plaursen** [comment]
Det er en oplagt kandidat for lidt tuning, jeg synes også det går for langsomt.

**Comment by janhebnes** [comment]
Første rundte er released på startlist.club men der er stadig 10 sekunders rendering på en ØSF liste, så der er mere at hente.

**Comment by plaursen** [comment]
Ja, det har hjulpet lidt, men ikke meget.

Hvis man vælger Billund, dukker alle ØSF elever også op ?!?
Ser ud til at være ok for andre end Billund

**Comment by plaursen** [comment]
Der er et eller andet galt med klub/datofilteret også...

**Comment by plaursen** [comment]
Stadig ikke godt nok.

En pilot uden træningsflyvning håndteres på 10-15ms. Det er vel ok.
En pilot med træningsflyvninger tager 100-150ms. Det er vel også ok-ish.

Men: når en klub har 273 piloter, så løber det op alligevel.


Ny ide til test:
1: Hent alle AppliedExercises (dem skal vi mere eller mindre bruge alligevel). Udtræk deres FlightId til brug i 2).
2: Hent flyvninger, hvori de indgår (projektion: Pilot, dato, flyvetid, ...), evt filtreret på klub.
3: Brug piloterne fra 2) til iteration gennem 1)
