### ISSUE TITLE
CSV export

### ISSUE THREAD

**Issue by plaursen** [janhebnes/startlist.club#12]
Vi skal kunne udtrække CSV til brug for opdatering af 
Elevmappen.
Vi skal ikke tage os af UI, men data skal kunne dække behovet i Elevmappe.pdf side 13 og 14

**Comment by plaursen** [comment]
[Elevmappe.pdf](https://github.com/janhebnes/startlist.club/files/5719146/Elevmappe.pdf)

**Comment by janhebnes** [comment]
Forudsætter data model er etableret.

**Comment by kuliktomas** [comment]
Har data modellen under review, men efter jeg har læst den pdf er ussikert hvad vi skal faktisk eksportere. Hvad med vejr forholdt for og de individuelle flyvninger? Kan den forklares lidt mere?

**Comment by plaursen** [comment]
AFventer input fra DTO (LAP) mht mere indhold
