### ISSUE TITLE
Etablering af hosting til startlistplus.

### ISSUE THREAD

**Issue by plaursen** [janhebnes/startlist.club#13]
Forslag: plusdemo.startlist.club

**Comment by janhebnes** [comment]
Startlist Plus deployment dev miljø etableret på http://dev.startlist.club/

**Comment by janhebnes** [comment]
Rebased training-ui on master and deploymed branch to http://dev.startlist.club/ from publish profile dev. 
Shared deployment password with Per. 

Training-ui branch or whatever development works that needs to be shown is now available to be published to http://dev.startlist.club/
