### ISSUE TITLE
Fejl ved indlæs af siden ved tryk på uddandelse under startliste

### ISSUE THREAD

**Issue by Micro1st** [janhebnes/startlist.club#131]
En af vores instruktør var inde på en elev for at indtast hans flyvning. Han siger den kom med en fejl, da han trykkede på Gem.
Det handler om Start nr. 11 i dag den 14-04-21 - NV (OY-NVX) | Christian Bane Mark Larsen | 13:35 | 14:45

https://startlist.club/VSK/TrainingLog/Edit?flightId=9e8aa1ba-282d-4fc8-97f7-5b9d8a9a7b01

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

**Comment by plaursen** [comment]
Tak, det ser jeg på asap (i morgen)

**Comment by plaursen** [comment]
Hm. Deløvelser for U18 og U19 optræder to gange - det burde ikke kunne lade sig gøre.

https://startlist.club/VSK/TrainingLogHistory?fromDate=04%2F12%2F2021%2000%3A00%3A00&toDate=04%2F15%2F2021%2000%3A00%3A00
