### ISSUE TITLE
Uddannelsesflyvninger

### ISSUE THREAD

**Issue by Micro1st** [janhebnes/startlist.club#141]
Man skal vælge en deløvelse i en norm ellers tæller den ikke med i uddannelsesflyvning. Det er ikke nok bare at skrive for SFIL, skrive en note eller manøvrer. Er det med vilje?

**Comment by plaursen** [comment]
Jeps. Set fra dto er en flyvning kun skoleflyvning hvis der foretaget mindst en grading.
