### ISSUE TITLE
Revider datamodeller relateret til elevlogbog.

### ISSUE THREAD

**Issue by plaursen** [janhebnes/startlist.club#21]
De er p.t. lavet ret meget on-the-fly ud fra hvad der var påkrævet for at lave en UI mockup.

Skal sandsynligvis gentænkes og reimplementeres.

**Comment by kuliktomas** [comment]
Jeg arbejde på den, har lavet tabellene og små tegning til de første par tabeller. Arbejder nu på at få data der er vist i UI at komme fra tabeller i stedet for enums.
[BasicTables.pdf](https://github.com/janhebnes/startlist.club/files/5842040/BasicTables.pdf)
[BasicTablesUI.pdf](https://github.com/janhebnes/startlist.club/files/5842041/BasicTablesUI.pdf)

**Comment by plaursen** [comment]
Super!

Kan se at du har fået pushet, jeg regner med at få lidt kode-tid i weekenden.

Er ved at rydde lidt op i ViewModels, det er lidt en sammenblanding af det 'statiske' (=træningsprogra,->lektionser_>øvelser) og det der er foretaget på den aktuelle flyvning, kan jeg se.


Det var også kodet med det simple formål at kunne vise et UI-forslag...
Regner med at det muligvis overlapper det du er ved at lave, så når jeg lige er kommet ind i det igen skal vi måske koordinere?

mvh
Per


Den 20. januar 2021 kl. 12.32.03 +01.00, skrev kuliktomas <notifications@github.com>:

**Comment by kuliktomas** [comment]
Jeg har nu lavet en db tabellene til manouvers (har lært at virke med Entity Framework :)), skal rydde op lidt nu (slette manouvre enums) og, tænke nu hvordan skal manouvre gemmes under flyvning. Jeg tænke mig at lave en many to many tabel mellem TrainingFlightAnnotations og Manourvre, der som jeg forstå den der kan være flere manouvrer i en training flyvning?

Når det er klar laver jeg en pull request så får vi første del på plads, og fokuserer jeg på notes og log. Vi kan godt koordinere i weekenden.

**Comment by kuliktomas** [comment]
![BasicTables](https://user-images.githubusercontent.com/31243070/105489309-516e0c00-5cb3-11eb-9a34-f567e634b4f6.jpg)
Ikke helt sikkert on SFIL endnu.

**Comment by kuliktomas** [comment]
Har tænkt modellen over og kan se at det skal være muligt at gemme flere end et instruktor kommentar til flyvning. Så uploader revidering.
[BasicTables.pdf](https://github.com/janhebnes/startlist.club/files/5862225/BasicTables.pdf)

**Comment by kuliktomas** [comment]
Så her er den endelige model til TrainingFlightAnnotations, som implementered
[DBModelTrainingLog.pdf](https://github.com/janhebnes/startlist.club/files/5938992/DBModelTrainingLog.pdf)

**Comment by kuliktomas** [comment]
Og så en datamodel til Training exerices:
[TrainingExercises.pdf](https://github.com/janhebnes/startlist.club/files/5939049/TrainingExercises.pdf)
