### ISSUE TITLE
Club editor is not activating Pilot editing

### ISSUE THREAD

**Issue by janhebnes** [janhebnes/startlist.club#36]
Live har vi en bruger som er sat som editor men som af en eller anden grund ikke får menu punktet piloter for vedkommendes klub.

![image](https://user-images.githubusercontent.com/910301/106602518-6a04de80-655d-11eb-9615-1c16a7d555d0.png)

Ingen bruger administration selv om Editor er sat... 
![image](https://user-images.githubusercontent.com/910301/106603074-2363b400-655e-11eb-938e-788ad1a27061.png)

**Comment by janhebnes** [comment]
@plaursen hvis du har tid måtte du gerne kig med på denne.

**Comment by plaursen** [comment]
_Layout.cshtml og PilotController kræver at man er Manager for at redigere Piloter. Det ser ret bevidst ud.

**Comment by janhebnes** [comment]
Dude...
