### ISSUE TITLE
SImpel backup/restore af træningsprogram plus afledte data (til udv-formål)

### ISSUE THREAD

**Issue by plaursen** [janhebnes/startlist.club#37]
Gem som JSON
Indlæs JSON
?

**Comment by janhebnes** [comment]
Husk seed data evt kan bruges i udv og som basis i først live

**Comment by plaursen** [comment]
> Husk seed data evt kan bruges i udv og som basis i først live

Yep. Det var for at slippe for at indtaste hele molevitten som seed data. Det er en smule tungt.  Nu har vi et CRUD UI til træningsprogrammer, og så tænkte jeg at vi lige gemmer når der er indtastst, så vi kan restore efter at DB er zappet af en eller anden grund.
