### ISSUE TITLE
Erstat manuel Seed af training program med load fra JSON

### ISSUE THREAD

**Issue by plaursen** [janhebnes/startlist.club#51]
Vi har nu JSON export/import, måske vi skulle bruge JSON til at Seed'e med ?

**Comment by plaursen** [comment]
Jo, load skal i givet fald ske derfra (som nu). Det er bare for at slippe for al den tekst, jeg gik kold efter A1 i sommer :)

**Comment by janhebnes** [comment]
Man kan snyde og lave sql som danner seed data koden

man. 22. feb. 2021 15.55 skrev plaursen <notifications@github.com>:

**Comment by kuliktomas** [comment]
Det vil jeg gerne kigge på

**Comment by janhebnes** [comment]
Vi har nu Seed Data med udgangspunkt i json filerne. 
https://github.com/janhebnes/startlist.club/commit/4e77a5b5050499a5feb785c7e27a516d2e85c057
