### ISSUE TITLE
Flyt hosting til Azure

### ISSUE THREAD

**Issue by plaursen** [janhebnes/startlist.club#52]
Kunne være dejligt at have på plads ca ved sæsonstart

**Comment by janhebnes** [comment]
Status er at miljøet er oppe med først lag productions databaser, men kæmper lidt med entity i 4.5 vs azure integrated security. 
Er meget aktiv på opgaven. 

Lige nu kan man køre actions fra github som servicerer release til de forskellige miljøer, og der eksperimenteres i azure-production branchen... 

To be continued.

**Comment by janhebnes** [comment]
Status er at hosting delen er klar. Der er en problem stilling på email hvor jeg skal overveje om jeg kan genbruge twillio til at sætte sendgrid på i stedet så vi kører hostede tjenester hele vejen.

Jeg har forbindelsen på plads til at kunne migrere data fra nuværende production til azure, men afventer lidt med at trykke på aftrækkerende. Der skal dog snart laves en prøve migrering af dataen på de forskellige miljøer. 

https er eksporteret men der er ikke opsat noget dns endnu, afventer vi er klar til data migrering og email er kørende på azure.

Der er forbindelse til github på deployment, det kan være det skal ændres til azure devops, når vi får set hvor langt man kommer på de gratis actions minutter der er på github projekterne.

**Comment by janhebnes** [comment]
Status er at SMS og E-mail er på plads fra Azure. 
Database migrerings flow er kørt med backup fra live. 

http://azure.startlist.club/ kører med kopi af live databasen. 

Der er lavet optimering af Flights tabellen med index som løste det performance problem der gjorde tingene fortsat ikke kørte hurtigere i https://github.com/janhebnes/startlist.club/commit/9a2269cfb64d8d4febb292ce43fce163ea7928db

**Comment by janhebnes** [comment]
https://github.com/janhebnes/startlist.club/issues/81

**Comment by janhebnes** [comment]
Status er at performance issues har vist sig at skyldes huller i hvor mange sql kald som lå i baggrunden og kørte, der er udvidet med sql tracing på dev, så man i fremtiden kan holde fokus på at holde mængden af sql operationer nede.

Vi er klar til at flytte til Azure når vi ønsker det. 
Lige nu kører vi på en MSDN sponsoreret subscription for at få det op at køre, denne bør udskiftes inden vi går rigtig live da der er et loft på udgiften i den opsætning, når vi skifter skal der kigges på at få sponsorater fra klubberne til driften.

**Comment by janhebnes** [comment]
Hosting er nu flyttet og aktiv på azure.
