### ISSUE TITLE
Planlæg deployment til production

### ISSUE THREAD

**Issue by plaursen** [janhebnes/startlist.club#54]
Vandtæt strategi for migration. Vi må ikke miste data!

Måske en staging.startlist.club, som er en klon af production, og som vi kan test-deploye til ?

**Comment by janhebnes** [comment]
Som udgangspunkt er brugen af Entity framework migration vandtæt... man kunne godt overveje en staging.startlist.club med kopi af data med x mellemrum.. Ser lige hvad azure hostingen giver os af muligheder.

**Comment by janhebnes** [comment]
Released today at 17 DK time
https://github.com/janhebnes/startlist.club/releases
