### ISSUE TITLE
Entity Framework LINQ på SQL Azure DB timer ud på Flight/Index

### ISSUE THREAD

**Issue by janhebnes** [janhebnes/startlist.club#81]
Når man besøger http://startlist.azurewebsites.net/%C3%98SF/Flight?skip=0 så får man timeout. 
Har eksperimenteret med om det er skip take, men når man slår dem helt fra i query opstår timeout fortsat. 

![image](https://user-images.githubusercontent.com/910301/111053040-d4644500-8460-11eb-8421-d861458d11e4.png)

**Comment by plaursen** [comment]
Prøvede lige at kaste dotTrace på den (kørt lokalt)

Der er ingen tvivl om at det er SQL queries der tager tiden, specielt et enkelt:

![image](https://user-images.githubusercontent.com/48796590/111061631-ac96d080-84a4-11eb-847e-0fea91c24a1c.png)




Kørte også dotMemory, og det så ret fredeligt ud. Ikke noget større memoryforbrug (i forhold til hvad jeg ser på arbejde :)

**Comment by plaursen** [comment]
SELECT 
    [UnionAll2].[AccessFailedCount] AS [C1], 
    [UnionAll2].[Id] AS [C2], 
    [UnionAll2].[BoundToPilotId] AS [C3], 
    [UnionAll2].[LastLogonTimeStamp] AS [C4], 
    [UnionAll2].[Email] AS [C5], 
    [UnionAll2].[EmailConfirmed] AS [C6], 
    [UnionAll2].[PasswordHash] AS [C7], 
    [UnionAll2].[SecurityStamp] AS [C8], 
    [UnionAll2].[PhoneNumber] AS [C9], 
    [UnionAll2].[PhoneNumberConfirmed] AS [C10], 
    [UnionAll2].[TwoFactorEnabled] AS [C11], 
    [UnionAll2].[LockoutEndDateUtc] AS [C12], 
    [UnionAll2].[LockoutEnabled] AS [C13], 
    [UnionAll2].[AccessFailedCount1] AS [C14], 
    [UnionAll2].[UserName] AS [C15], 
    [UnionAll2].[C1] AS [C16], 
    [UnionAll2].[UserId] AS [C17], 
    [UnionAll2].[RoleId] AS [C18], 
    [UnionAll2].[UserId1] AS [C19], 
    [UnionAll2].[C2] AS [C20], 
    [UnionAll2].[C3] AS [C21], 
    [UnionAll2].[C4] AS [C22], 
    [UnionAll2].[C5] AS [C23], 
    [UnionAll2].[C6] AS [C24], 
    [UnionAll2].[C7] AS [C25], 
    [UnionAll2].[C8] AS [C26], 
    [UnionAll2].[C9] AS [C27]
    FROM  (SELECT 
        CASE WHEN ([Extent2].[UserId] IS NULL) THEN CAST(NULL AS int) ELSE 1 END AS [C1], 
        [Limit1].[AccessFailedCount] AS [AccessFailedCount], 
        [Limit1].[Id] AS [Id], 
        [Limit1].[BoundToPilotId] AS [BoundToPilotId], 
        [Limit1].[LastLogonTimeStamp] AS [LastLogonTimeStamp], 
        [Limit1].[Email] AS [Email], 
        [Limit1].[EmailConfirmed] AS [EmailConfirmed], 
        [Limit1].[PasswordHash] AS [PasswordHash], 
        [Limit1].[SecurityStamp] AS [SecurityStamp], 
        [Limit1].[PhoneNumber] AS [PhoneNumber], 
        [Limit1].[PhoneNumberConfirmed] AS [PhoneNumberConfirmed], 
        [Limit1].[TwoFactorEnabled] AS [TwoFactorEnabled], 
        [Limit1].[LockoutEndDateUtc] AS [LockoutEndDateUtc], 
        [Limit1].[LockoutEnabled] AS [LockoutEnabled], 
        [Limit1].[AccessFailedCount] AS [AccessFailedCount1], 
        [Limit1].[UserName] AS [UserName], 
        [Extent2].[UserId] AS [UserId], 
        [Extent2].[RoleId] AS [RoleId], 
        [Extent2].[UserId] AS [UserId1], 
        CAST(NULL AS int) AS [C2], 
        CAST(NULL AS varchar(1)) AS [C3], 
        CAST(NULL AS varchar(1)) AS [C4], 
        CAST(NULL AS varchar(1)) AS [C5], 
        CAST(NULL AS varchar(1)) AS [C6], 
        CAST(NULL AS varchar(1)) AS [C7], 
        CAST(NULL AS varchar(1)) AS [C8], 
        CAST(NULL AS varchar(1)) AS [C9]
        FROM   (SELECT TOP (1) 
            [Extent1].[Id] AS [Id], 
            [Extent1].[BoundToPilotId] AS [BoundToPilotId], 
            [Extent1].[LastLogonTimeStamp] AS [LastLogonTimeStamp], 
            [Extent1].[Email] AS [Email], 
            [Extent1].[EmailConfirmed] AS [EmailConfirmed], 
            [Extent1].[PasswordHash] AS [PasswordHash], 
            [Extent1].[SecurityStamp] AS [SecurityStamp], 
            [Extent1].[PhoneNumber] AS [PhoneNumber], 
            [Extent1].[PhoneNumberConfirmed] AS [PhoneNumberConfirmed], 
            [Extent1].[TwoFactorEnabled] AS [TwoFactorEnabled], 
            [Extent1].[LockoutEndDateUtc] AS [LockoutEndDateUtc], 
            [Extent1].[LockoutEnabled] AS [LockoutEnabled], 
            [Extent1].[AccessFailedCount] AS [AccessFailedCount], 
            [Extent1].[UserName] AS [UserName]
            FROM [dbo].[AspNetUsers] AS [Extent1]
            WHERE [Extent1].[Id] = @p__linq__0 ) AS [Limit1]
        LEFT OUTER JOIN [dbo].[AspNetUserRoles] AS [Extent2] ON [Limit1].[Id] = [Extent2].[UserId]
    UNION ALL
        SELECT 
        2 AS [C1], 
        [Limit2].[AccessFailedCount] AS [AccessFailedCount], 
        [Limit2].[Id] AS [Id], 
        [Limit2].[BoundToPilotId] AS [BoundToPilotId], 
        [Limit2].[LastLogonTimeStamp] AS [LastLogonTimeStamp], 
        [Limit2].[Email] AS [Email], 
        [Limit2].[EmailConfirmed] AS [EmailConfirmed], 
        [Limit2].[PasswordHash] AS [PasswordHash], 
        [Limit2].[SecurityStamp] AS [SecurityStamp], 
        [Limit2].[PhoneNumber] AS [PhoneNumber], 
        [Limit2].[PhoneNumberConfirmed] AS [PhoneNumberConfirmed], 
        [Limit2].[TwoFactorEnabled] AS [TwoFactorEnabled], 
        [Limit2].[LockoutEndDateUtc] AS [LockoutEndDateUtc], 
        [Limit2].[LockoutEnabled] AS [LockoutEnabled], 
        [Limit2].[AccessFailedCount] AS [AccessFailedCount1], 
        [Limit2].[UserName] AS [UserName], 
        CAST(NULL AS varchar(1)) AS [C2], 
        CAST(NULL AS varchar(1)) AS [C3], 
        CAST(NULL AS varchar(1)) AS [C4], 
        [Extent4].[Id] AS [Id1], 
        [Extent4].[UserId] AS [UserId], 
        [Extent4].[ClaimType] AS [ClaimType], 
        [Extent4].[ClaimValue] AS [ClaimValue], 
        CAST(NULL AS varchar(1)) AS [C5], 
        CAST(NULL AS varchar(1)) AS [C6], 
        CAST(NULL AS varchar(1)) AS [C7], 
        CAST(NULL AS varchar(1)) AS [C8]
        FROM   (SELECT TOP (1) 
            [Extent3].[Id] AS [Id], 
            [Extent3].[BoundToPilotId] AS [BoundToPilotId], 
            [Extent3].[LastLogonTimeStamp] AS [LastLogonTimeStamp], 
            [Extent3].[Email] AS [Email], 
            [Extent3].[EmailConfirmed] AS [EmailConfirmed], 
            [Extent3].[PasswordHash] AS [PasswordHash], 
            [Extent3].[SecurityStamp] AS [SecurityStamp], 
            [Extent3].[PhoneNumber] AS [PhoneNumber], 
            [Extent3].[PhoneNumberConfirmed] AS [PhoneNumberConfirmed], 
            [Extent3].[TwoFactorEnabled] AS [TwoFactorEnabled], 
            [Extent3].[LockoutEndDateUtc] AS [LockoutEndDateUtc], 
            [Extent3].[LockoutEnabled] AS [LockoutEnabled], 
            [Extent3].[AccessFailedCount] AS [AccessFailedCount], 
            [Extent3].[UserName] AS [UserName]
            FROM [dbo].[AspNetUsers] AS [Extent3]
            WHERE [Extent3].[Id] = @p__linq__0 ) AS [Limit2]
        INNER JOIN [dbo].[AspNetUserClaims] AS [Extent4] ON [Limit2].[Id] = [Extent4].[UserId]
    UNION ALL
        SELECT 
        3 AS [C1], 
        [Limit3].[AccessFailedCount] AS [AccessFailedCount], 
        [Limit3].[Id] AS [Id], 
        [Limit3].[BoundToPilotId] AS [BoundToPilotId], 
        [Limit3].[LastLogonTimeStamp] AS [LastLogonTimeStamp], 
        [Limit3].[Email] AS [Email], 
        [Limit3].[EmailConfirmed] AS [EmailConfirmed], 
        [Limit3].[PasswordHash] AS [PasswordHash], 
        [Limit3].[SecurityStamp] AS [SecurityStamp], 
        [Limit3].[PhoneNumber] AS [PhoneNumber], 
        [Limit3].[PhoneNumberConfirmed] AS [PhoneNumberConfirmed], 
        [Limit3].[TwoFactorEnabled] AS [TwoFactorEnabled], 
        [Limit3].[LockoutEndDateUtc] AS [LockoutEndDateUtc], 
        [Limit3].[LockoutEnabled] AS [LockoutEnabled], 
        [Limit3].[AccessFailedCount] AS [AccessFailedCount1], 
        [Limit3].[UserName] AS [UserName], 
        CAST(NULL AS varchar(1)) AS [C2], 
        CAST(NULL AS varchar(1)) AS [C3], 
        CAST(NULL AS varchar(1)) AS [C4], 
        CAST(NULL AS int) AS [C5], 
        CAST(NULL AS varchar(1)) AS [C6], 
        CAST(NULL AS varchar(1)) AS [C7], 
        CAST(NULL AS varchar(1)) AS [C8], 
        [Extent6].[LoginProvider] AS [LoginProvider], 
        [Extent6].[ProviderKey] AS [ProviderKey], 
        [Extent6].[UserId] AS [UserId], 
        [Extent6].[UserId] AS [UserId1]
        FROM   (SELECT TOP (1) 
            [Extent5].[Id] AS [Id], 
            [Extent5].[BoundToPilotId] AS [BoundToPilotId], 
            [Extent5].[LastLogonTimeStamp] AS [LastLogonTimeStamp], 
            [Extent5].[Email] AS [Email], 
            [Extent5].[EmailConfirmed] AS [EmailConfirmed], 
            [Extent5].[PasswordHash] AS [PasswordHash], 
            [Extent5].[SecurityStamp] AS [SecurityStamp], 
            [Extent5].[PhoneNumber] AS [PhoneNumber], 
            [Extent5].[PhoneNumberConfirmed] AS [PhoneNumberConfirmed], 
            [Extent5].[TwoFactorEnabled] AS [TwoFactorEnabled], 
            [Extent5].[LockoutEndDateUtc] AS [LockoutEndDateUtc], 
            [Extent5].[LockoutEnabled] AS [LockoutEnabled], 
            [Extent5].[AccessFailedCount] AS [AccessFailedCount], 
            [Extent5].[UserName] AS [UserName]
            FROM [dbo].[AspNetUsers] AS [Extent5]
            WHERE [Extent5].[Id] = @p__linq__0 ) AS [Limit3]
        INNER JOIN [dbo].[AspNetUserLogins] AS [Extent6] ON [Limit3].[Id] = [Extent6].[UserId]) AS [UnionAll2]
    ORDER BY [UnionAll2].[Id] ASC, [UnionAll2].[C1] ASC

**Comment by janhebnes** [comment]
Resolved in https://github.com/janhebnes/startlist.club/commit/82f804bc8dad155a88d9b4c7ad3f11df3d641933
