### ISSUE TITLE
signalR på Flight / Grid trigges kun et sted fra

### ISSUE THREAD

**Issue by plaursen** [janhebnes/startlist.club#84]
Vi har flere måder hvorpå dagens flyvninger (Grid) kan opdateres.

For nuværende er det kun én (?) som trigger en signalR notifikation om ændriger.

ENten skal vi dække alle situationer client side, eller triggeren skal være server side (jeg hælder til det sidste)

**Comment by kuliktomas** [comment]
Jeg laver den på server side.

**Comment by plaursen** [comment]
Er gjort20. mar. 2021 13.07 skrev kuliktomas ***@***.***>:

Jeg laver den på server side.

**Comment by plaursen** [comment]
Tomas, det er lavet.
Se PR:
https://github.com/janhebnes/startlist.club/pull/96
