### ISSUE TITLE
Fremhæv (dagens?) skoleflyvninger som ikke er registreret som skoleflyvninger

### ISSUE THREAD

**Issue by plaursen** [janhebnes/startlist.club#91]
For at undgå registreringseftersløb, kunne det være fikst at fremhæve flyvninger som:
1) Har en elev i forsædet (eller solo)
2) Ikke har AppliedExercise registreringer på flyvningen (evt også TrainingFlightAnnotation)

Identifikation af elev kan være lidt svært at gøre entydigt,. Da en pilot jo godt på samme dag kan være
1) Instruktør
2) Alm pilot
3) Elev (TMG rettighed f.ex.)

En pragmatisk tilgang kan være ok, det behøver ikke at være uden huller så længe det bare er en fremhævning.

**Comment by plaursen** [comment]
Kunne også vendes rundt, så instruktøren kan se på dagsrapporten, hvilke flyvninger han/hun har deltaget i, som ikke har skolingsregistreringer.

**Comment by plaursen** [comment]
Måske en lavpraktisk ting som at tagge et fly som 'skolefly', og baesere fremhævningen på det:

Skolefly & landet & now-Tland > 20 min => highlight

**Comment by janhebnes** [comment]
hvad hvis man kører at det er synligt på **Trænings** ikonet når der er foretaget registreringer i tilknytning til flyvningen, så kan man se de som har fået trænings registreringer og de som ikke har ?

**Comment by plaursen** [comment]
Som f.ex sådan?:
![image](https://user-images.githubusercontent.com/48796590/112595113-4138f100-8e0a-11eb-90fe-ce94f6d1e471.png)
